export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST';
export const CREATE_ENTTRY_SUCCESS = 'CREATE_ENTTRY_SUCCESS';
export const CREATE_ENTTRY_FAILURE = 'CREATE_ENTTRY_FAILURE';

export const EDIT_ENTRY_REQUEST = 'EDIT_ENTRY_REQUEST';
export const EDIT_ENTRY_SUCCESS = 'EDIT_ENTRY_SUCCESS';
export const EDIT_ENTRY_FAILURE = 'EDIT_ENTRY_FAILURE';

export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';

export const VIEW_ENTRY_REQUEST = 'VIEW_ENTRY_REQUEST';
export const VIEW_ENTRY_SUCCESS = 'VIEW_ENTRY_SUCCESS';
export const VIEW_ENTRY_FAILURE = 'VIEW_ENTRY_FAILURE';

export const VIEW_ENTRIES_REQUEST = 'VIEW_ENTRIES_REQUEST';
export const VIEW_ENTRIES_SUCCESS = 'VIEW_ENTRIES_SUCCESS';
export const VIEW_ENTRIES_FAILURE = 'VIEW_ENTRIES_FAILURE';
